EduMIPS64/edumips64

contrib/kate_mips.xml

Here the pull request for the  syntax highlighting xml of kate for eduMips64. As soon as possibile the vim one.
Bye

Adding kate syntax highlighting xml file

---

docs/developer-guide.md

Remove mention of Cloud9, free instances are too small for GWT

---

docs/developer-guide.md

Add documentation about unit tests

---

docs/design/web-ui-stories.md
docs/developer-guide.md

Closes #85 and makes some progress towards #70.

Documentation updates

---

src/main/java/org/edumips64/utils/io/StringWriter.java
src/main/java/org/edumips64/utils/io/Writer.java
src/test/java/org/edumips64/CpuTests.java
src/test/resources/hello-world.s

Add unit test for SYSCALL 5

---

readme.md

Fixes #73
ReadTheDocs has been configured to build/serve both English and Italian.

Update readme.md with ReadTheDocs links

---

readme.md

Fix style of waffle.io and add codecov.

Update README badges

---

src/main/java/org/edumips64/ui/common/CycleElement.java
src/test/java/org/edumips64/BaseTest.java
src/test/java/org/edumips64/EndToEndTests.java

Includes a bunch of small fixes done during the troubleshooting process.

Fix state warnings for WAW after RAW

---

CODE_OF_CONDUCT.md
readme.md

Adopt the Contributor Covenant Code of Conduct

---

src/main/java/org/edumips64/Main.java
src/main/java/org/edumips64/ui/swing/DineroFrontend.java
src/main/java/org/edumips64/ui/swing/GUICode.java
src/main/java/org/edumips64/ui/swing/GUIComponent.java
src/main/java/org/edumips64/ui/swing/GUIConfig.java
src/main/java/org/edumips64/ui/swing/GUICycles.java
src/main/java/org/edumips64/ui/swing/GUIData.java
src/main/java/org/edumips64/ui/swing/GUIIO.java
src/main/java/org/edumips64/ui/swing/GUIRegisters.java
src/main/java/org/edumips64/ui/swing/GUIStatistics.java
src/main/java/org/edumips64/utils/ConfigKey.java
src/main/java/org/edumips64/utils/ConfigStore.java
src/main/java/org/edumips64/utils/CurrentLocale.java

Implement support for changing font size

---

src/main/java/org/edumips64/Main.java

Last fixes to scale font

---

build.xml
docs/developer-guide.md
readme.md
src/main/java/org/edumips64/core/CPU.java
src/main/java/org/edumips64/core/Pipeline.java
src/test/java/org/edumips64/BaseWithInstructionBuilderTest.java
src/test/java/org/edumips64/EndToEndTests.java
src/test/java/org/edumips64/core/PipelineTest.java

Do some refactoring needed to help thinking about issue #48.

Minor improvements on the way to fix Issue #48

---

src/main/java/org/edumips64/ui/swing/GUIConfig.java

Not sure how it ended up in here, I am assuming I selected the wrong
import at some point.

Remove spurious CORBA import

---

build.gradle
gradlew
gradlew.bat

Remove Gradle wrapper version restriction and update the wrapper itself.

Update Gradle wrapper

---

WORKSPACE
docs/developer-guide.md
src/main/java/org/edumips64/BUILD
src/main/java/org/edumips64/core/BUILD
src/main/java/org/edumips64/core/CPU.java
src/main/java/org/edumips64/core/Pipeline.java
src/main/java/org/edumips64/core/fpu/BUILD
src/main/java/org/edumips64/core/is/BUILD
src/main/java/org/edumips64/core/parser/BUILD
src/main/java/org/edumips64/ui/swing/BUILD
src/main/java/org/edumips64/ui/swing/GUICode.java
src/main/java/org/edumips64/ui/swing/GUIPipeline.java
src/main/java/org/edumips64/ui/swing/img/BUILD
src/main/java/org/edumips64/utils/BUILD
src/main/java/org/edumips64/utils/CycleBuilder.java
src/main/java/org/edumips64/utils/io/BUILD
src/main/resources/images/BUILD
src/test/java/org/edumips64/BUILD
src/test/java/org/edumips64/core/BUILD
src/test/java/org/edumips64/core/PipelineTest.java
src/test/java/org/edumips64/core/fpu/BUILD
src/test/resources/BUILD
src/test/resources/utils/BUILD

Initial batch of work for #180. Some features are still missing.

Initial Bazel support

---

docs/BUILD
docs/user/common_conf.py
docs/user/it/BUILD
src/main/java/org/edumips64/BUILD
src/main/java/org/edumips64/Main.java
src/main/java/org/edumips64/ui/swing/GUIHelp.java

Work towards #180. The help compiles, but it still not in the right position in the JAR. Suspending this effort for now because it might actually be easier to migrate to a WebView (#188) and not have to deal with the JavaHelp twists of URLs, Classloaders and similar.

Some steps towards compiling the help with Bazel

---

build.xml
src/main/java/org/edumips64/BUILD

Fixes #195 and also ticks one box in #180.

Fix splash screen image path

---

utils/bazel-stamp.sh

Shorten the SHA1 of the commit, add repo name and branch name.

Improve the Git revision added to the JAR

---

.gitignore
.project/.bazelproject

Also ignore the .project/.blaze directory.

Add Bazel project view

---

src/main/java/org/edumips64/core/Memory.java
src/main/java/org/edumips64/core/parser/Parser.java
src/main/java/org/edumips64/utils/CurrentLocale.java
src/test/java/org/edumips64/EndToEndTests.java
src/test/java/org/edumips64/core/ParserTest.java
src/test/resources/large-offsets.s
src/test/resources/negative-offsets.s

Fix limit for offsets and allow for negative offsets

---

docs/user/en/src/user-interface.rst
docs/user/it/src/user-interface.rst
src/main/java/org/edumips64/Main.java
src/main/java/org/edumips64/core/CPU.java
src/main/java/org/edumips64/ui/swing/StatusBar.java

Also update the docs to mention it.
Fixes #78.

Display the CPU status in the status bar

---

build.gradle

As in https://github.com/codecov/example-gradle
Using this plugin: https://docs.gradle.org/current/userguide/jacoco_plugin.html

Add gradle task for code coverage

---

CHANGELOG.md
docs/user/en/src/instructions.rst
docs/user/it/src/instructions.rst
src/main/java/org/edumips64/core/is/DMULU.java
src/main/java/org/edumips64/core/is/InstructionBuilder.java
src/main/java/org/edumips64/core/parser/Parser.java
src/test/java/org/edumips64/EndToEndTests.java
src/test/resources/dmulu-simple-test.s

Add DMULU alias for DMULTU

---

src/main/java/org/edumips64/core/fpu/FPInstructionUtils.java
src/main/java/org/edumips64/core/is/BC1F.java
src/main/java/org/edumips64/core/is/BC1T.java
src/main/java/org/edumips64/core/is/CVT_D_L.java
src/main/java/org/edumips64/core/is/CVT_D_W.java
src/main/java/org/edumips64/core/is/CVT_L_D.java
src/main/java/org/edumips64/core/is/CVT_W_D.java
src/main/java/org/edumips64/core/is/FPArithmeticInstructions.java
src/main/java/org/edumips64/core/is/FPC_cond_DInstructions.java
src/main/java/org/edumips64/core/is/FPConditionalBranchesInstructions.java
src/main/java/org/edumips64/core/is/FPConditionalCC_DMoveInstructions.java
src/main/java/org/edumips64/core/is/FPConditionalZerosMoveInstructions.java
src/main/java/org/edumips64/core/is/FPFormattedOperandMoveInstructions.java
src/main/java/org/edumips64/core/is/FPMoveToAndFromInstructions.java
src/main/java/org/edumips64/ui/swing/GUIRegisters.java
src/main/java/org/edumips64/ui/swing/GUIStatistics.java
src/main/java/org/edumips64/utils/CycleElement.java
src/main/java/org/edumips64/utils/io/LocalReader.java
src/test/java/org/edumips64/EndToEndTests.java

More Codacity issues for #222. I left some of the instances alone where I didn't think it made a worthwhile improvement. If you disagree, I'd be happy to clean up other cases as well.

Codacity fixes

---

RELEASE_NOTES
src/main/java/org/edumips64/Main.java
src/main/java/org/edumips64/core/parser/Parser.java

Fix ReportDialog's code loading logic

---

build.gradle

This will address the issue raised in #276, which I'll fix once I release new JARs for 1.2.6.

Fix release JARs (Java version, images/docs in slim JAR)

---

src/main/java/org/edumips64/core/Converter.java
src/main/java/org/edumips64/core/parser/Parser.java
src/test/java/org/edumips64/core/ConverterIsHexNumberTest.java
src/test/java/org/edumips64/core/ConverterIsImmediateTest.java
src/test/java/org/edumips64/core/ConverterIsIntegerTest.java

Add unit tests, make them more efficient and fix bugs discovered while adding unit tests.

Improve numeric check functions

---

build.gradle
docs/user/en/src/examples.rst
docs/user/en/src/fpu.rst
docs/user/en/src/index.rst
docs/user/en/src/instructions.rst
docs/user/en/src/source-files-format.rst
docs/user/en/src/user-interface.rst
docs/user/it/src/examples.rst
docs/user/it/src/fpu.rst
docs/user/it/src/index.rst
docs/user/it/src/instructions.rst
docs/user/it/src/source-files-format.rst
docs/user/it/src/user-interface.rst

Fix RST warnings

---

build.gradle
docs/developer-guide.md

dev mode does not work, but this is a very good
starting point.
Fixes #228.

Fix build of GWT JS code

---

RELEASE_NOTES.md

This will help automating releases (#235).

Move release notes to Markdown

---

src/main/java/org/edumips64/Main.java
src/main/java/org/edumips64/MainCLI.java
src/main/java/org/edumips64/ui/swing/CPUSwingWorker.java

Remove most static fields from Main. This will make it possible to properly initialize it in unit tests.

Make Main non-static

---

build.gradle.kts
src/main/java/org/edumips64/Main.java
src/main/java/org/edumips64/MainCLI.java
src/main/java/org/edumips64/ui/swing/CPUSwingWorker.java
src/main/java/org/edumips64/utils/MetaInfo.java

This will help distinguish JARs coming from CI.

Augment version number for CI builds

---

src/main/java/org/edumips64/utils/CycleElement.java
src/test/java/org/edumips64/EndToEndTests.java

Also fix a unit test that didn't fail as it should have and improve the logging of this issue.
Fixes #315.

Consider DIV a valid state after RAW

---

scripts/edumips64-snap-wrapper.sh
snapcraft.yaml

Some things still don't work, the package is pushed to the snap repo but in the `edge` channel.
Work towards #8.

Basic support for snap packages

---

scripts/edumips64-snap-wrapper.sh
snapcraft.yaml

Small changes to the snap config and script, which still aren't working
as intended.
Still working towards #8.

Add shebang to script and dump section

---

build.gradle.kts
snapcraft.yaml

- add help in standaloneJar
- add non-headless JDK
- remove Gnome dependency
- simplify snap config

Improve snap support

---

build.gradle.kts
docs/developer-guide.md
src/main/java/org/edumips64/client/edumips64.html
src/main/java/org/edumips64/webclient.gwt.xml

Fix GWT dev mode

---

.github/workflows/deploy.yml

* keep commit history;
* add FQDN;
* improve commit message.

Update web UI deploy action

---

src/main/java/org/edumips64/client/WebUi.java
src/main/java/org/edumips64/client/style.css
src/main/java/org/edumips64/client/ui.js
src/main/java/org/edumips64/core/Register.java
src/main/java/org/edumips64/webclient.gwt.xml

This is a simple, not-very-useful change, but it explores a way to export JSON across the Java/JS boundary.

Add table-based registers to WebUI

---

docs/design/web-ui-roadmap.md

Also, rename the file to web-ui-roadmap.md

Add link to GitHub project to the Alpha milestone

---

src/main/java/org/edumips64/client/FluentJsonObject.java
src/main/java/org/edumips64/client/WebUi.java
src/main/java/org/edumips64/client/ui.js
src/main/java/org/edumips64/core/fpu/RegisterFP.java

Simple visualization of all registers

---

src/main/java/org/edumips64/client/CPUStepStatus.java
src/main/java/org/edumips64/client/FluentJsonObject.java
src/main/java/org/edumips64/client/Result.java
src/main/java/org/edumips64/client/WebUi.java
src/main/java/org/edumips64/client/ui.js

Refactor GWT and JS code to prepare for single-stepping

---

src/main/java/org/edumips64/client/index.html
src/main/java/org/edumips64/client/style.css
src/main/java/org/edumips64/client/ui.js

* adopt CSS Grid layout;
* add the Materialize CSS library and add a navbar + about button;
* clean up useless CSS classes;
* clean up CSS.

Clean up CSS and add the Materialize CSS library

---

src/main/java/org/edumips64/client/Instruction.java
src/main/java/org/edumips64/client/Pipeline.java
src/main/java/org/edumips64/client/WebUi.java
src/main/java/org/edumips64/client/index.html
src/main/java/org/edumips64/client/ui.js

Add a basic table-based pipeline view

---

src/main/java/org/edumips64/client/Instruction.java
src/main/java/org/edumips64/client/Pipeline.java
src/main/java/org/edumips64/client/Result.java
src/main/java/org/edumips64/client/ResultFactory.java
src/main/java/org/edumips64/client/Simulator.java
src/main/java/org/edumips64/client/Worker.java
src/main/java/org/edumips64/client/static/ui.js

* add file-level comments;
* add missing <tbody> tag for the Pipeline widget;
* move FromCpuStatus to ResultFactory;
* remove unneeded specification of the JS namespace.

Small fixes for the GWT/JS code

---

src/main/java/org/edumips64/client/Result.java
src/main/java/org/edumips64/client/Simulator.java
src/main/java/org/edumips64/client/static/ui.js

Implement support for the BREAK instruction

---

docs/developer-guide.md

Clarify dev docs on the Web UI

---

src/webapp/components/Code.js
src/webapp/components/Controls.js
src/webapp/components/Simulator.js
src/webapp/static/style.css

* move Controls out;
* enable autoResize;
* fix padding.

Improve editor appearance

---

src/webapp/components/Code.js
src/webapp/components/Simulator.js
src/webapp/static/index.html
src/webapp/static/style.css

Show CPU stages in the Monaco editor

---

package-lock.json
package.json
src/webapp/components/Simulator.js
src/webapp/index.js
src/webapp/static/style.css
webpack.config.js

Track version of the web UI, which for now is just the commit hash,
show it on the main page and push it to telemetry as an extra dimension.

feat(web): version logging/tracking

---

renovate.json

fix(renovate): fix JSON syntax

---

src/webapp/index.js

This improves filtering ability in the dashboards.

feat(web): set environment as role name

---

src/main/java/org/edumips64/utils/CycleElement.java

Fixes a "Use Equals To Compare String" item from the Codacity issues.
See https://github.com/EduMIPS64/edumips64/issues/222

Fixes a "Use Equals To Compare String"

---

.github/workflows/gradle.yml
build.gradle.kts
docs/developer-guide.md

Closes #476 and removes the build-time dependency GNU Make.

Remove make dependency and fix missing help in JAR

---

build.gradle.kts
docs/developer-guide.md

Also improve a bit the MSI generation logic and update dev docs.
Fixes #465.

fix: remove version tweak for MSI

---

webpack.config.js

Also add source map and dev/build modes.

fix: update webpack serve cfg

---

.github/workflows/pr-deploy.yml
package-lock.json
package.json
playwright.config.js
src/test/webapp/basic-tests.spec.js
src/test/webapp/localhost-available.spec.js
webpack.config.js

The tests will be run for every PR against the test code deployed as part of the PR process.

feat(test): add very basic UI tests

---

.github/workflows/deploy.yml
.github/workflows/pr-deploy.yml

feat: use Github Action for deployments

---

src/main/java/org/edumips64/core/is/Instruction.java
src/main/java/org/edumips64/core/parser/Parser.java

* add documentation for the instruction syntax
* refactor parameter parsing code to reduce duplication and improve readability

refactor: improve some bits of Parser

---

package-lock.json
package.json
webpack.config.js

fix: small fixes to package.json

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

This should add compatibility with JDK 16.

chore: update gradle-wrapper to 7.3

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
build.gradle.kts
snapcraft.yaml

I've been having issues with VSCode errors, only a JDK update seems to
fix them.

chore: update JDK to 17

---

snapcraft.yaml

fix: add zlib headers

---

CHANGELOG.md
src/main/java/org/edumips64/utils/CycleBuilder.java
src/test/java/org/edumips64/EndToEndTests.java
src/test/resources/issue-646-twodiv.s

This fixes a rendering issue with chained div.d instructions.
Also add a regression test for this issue based on code provided by
@jcarletta.
Fixes #646

fix: increment lookback for CycleBuilder component

---

docs/developer-guide.md

In the developer guide, there was a typo in line 166 which has been fixed.

fixed typo in developer guide

---

.github/workflows/ci.yml

This should mitigate the race conditions caused by multiple PRs trying to deploy at the same time to GitHub Pages.

feat: deploy web UI to Azure blob storage on PRs

---

docs/user/en/src/instructions.rst
docs/user/it/src/instructions.rst

Renaming SLTUI to SLTIU in documentation

---

docs/user/en/src/instructions.rst
docs/user/it/src/instructions.rst

fix(doc): update BGEZ docs

---

.github/workflows/ci.yml

This was broken in version 1.1.1.
Fixes #774.

fix: use correct attribute for read-properties

---

.readthedocs.yaml

Tries to patch readthedocs generation. Should close #788.
Also build pdf & epub formats, hope nothing goes wrong

Add: readthedocs configuration

---

src/test/webapp/basic-tests.spec.js
src/webapp/static/style.css

fix(test): fix web UI tests

---

.devcontainer/devcontainer.json
docs/developer-guide.md

feat: improve dev container

---

src/webapp/index.js

Exploring the App Insights API and backend to fix #731.

feat(web): add basic telemetry for key actions

---

snapcraft.yaml

Trying to fix failed builds on snapcraft.io

Run default snapcraft build action

---

snapcraft.yaml

Should fix the failed builds on snapcraft.io

fix(snap): set HTTP proxy host/port

---

scripts/edumips64-snap-wrapper.sh

fix: add UTF8 file encoding option to snap

---

src/webapp/components/Code.js

fix(web): fix 2 code editor bugs

---

src/main/java/org/edumips64/utils/CycleBuilder.java

fix: always show first instruction in GUICycles

---

.github/workflows/ci.yml

OpenID Connect should be set up, so this login method should work.

fix: update Azure login method

---

snapcraft.yaml

fix(snap): add python-3.10-venv

---

src/main/java/org/edumips64/utils/cli/Cli.java
src/main/java/org/edumips64/utils/cli/RunCommand.java
src/main/java/org/edumips64/utils/io/StdOutWriter.java

Fixes SYSCALL 5 not implemented in CLI mode #1178

fix: add SYSCALL 5 support to CLI

---

src/webapp/components/Registers.js
src/webapp/components/Statistics.js
src/webapp/css/main.css

fix(web): fix the registers font and the statistics layout

---

package-lock.json
package.json
src/webapp/components/Code.js
src/webapp/components/Header.js
src/webapp/components/Settings.js
src/webapp/components/Simulator.js

- added load/save code functionality to the main code panel
- added a new Settings component in the sidebar
- implemented vi-mode and font size controls into the Settings section

Editor features and new Settings component

---

.github/workflows/ci.yml

Fixes The deployments API action does not work with external contributors #617

fix(dev): do not fail deployments for external contributors

---

package-lock.json
src/webapp/components/Settings.js
src/webapp/components/Simulator.js

Settings tab color made coherent with the other sections. 
Overal improvement of the look for the side sections titles (see pic)

Tab fix & cosmetics

---

.github/workflows/ci.yml

Also needed to:
* create a Staging environment in GitHub and add the Azure secrets to it
* add a new Azure federated credential for repo:EduMIPS64/edumips64:environment:Staging

fix(dev): use a Staging env for verifying web UI from PRs

---

.github/workflows/ci.yml

This should allow us to build/test what is in the PR.

fix: checkout PR HEAD in CI

---

src/webapp/components/Simulator.js

Fixes Web UI: Reset CPU status when opening a file after execution of a program #1320

fix(web): reset CPU state when loading a file
