.travis.yml
This should fix the broken Travis CI build.
=> Remove deprecated --use-mirrors pip option

src/main/java/org/edumips64/core/Parser.java, src/test/java/org/edumips64/core/ParserTest.java
Fixes #95.
This issue came into existence because we had to get rid of BufferedReader,
since it's not supported by GWT.
=> Use \r\n as a line separator as well as \n

docs/user/en/src/source-files-format.rst, docs/user/it/src/source-files-format.rst, src/main/java/org/edumips64/core/Parser.java, src/test/java/org/edumips64/core/ParserTest.java
Fix the bound checking logic, make it emit errors, add unit tests and update
the relative documentation.
Fixes #1.
=> Correctly emit errors parsing out-of-bounds data

src/test/java/org/edumips64/EndToEndTests.java, src/test/resources/fpu-out-of-order-terminate.s
And also implement the machinery to add FP registers to the CpuStatus, to
allow FP registers verification in unit tests.
=> Add test for out-of-order ADD.D execution

src/test/java/org/edumips64/EndToEndTests.java
Fixes #125. The error made the tests depending on the ordering.
=> Fix typo in unit tests

src/main/java/org/edumips64/Main.java, src/main/java/org/edumips64/core/CPU.java, src/main/java/org/edumips64/core/is/InstructionBuilder.java, src/main/java/org/edumips64/ui/swing/CPUGUIThread.java, src/main/java/org/edumips64/ui/swing/DineroFrontend.java, src/main/java/org/edumips64/ui/swing/GUICode.java, src/main/java/org/edumips64/ui/swing/GUIConfig.java, src/main/java/org/edumips64/ui/swing/GUICycles.java, src/main/java/org/edumips64/ui/swing/GUIData.java, src/main/java/org/edumips64/ui/swing/GUIPipeline.java, src/main/java/org/edumips64/ui/swing/GUIRegisters.java, src/main/java/org/edumips64/utils/ConfigKey.java, src/main/java/org/edumips64/utils/ConfigStore.java, src/main/java/org/edumips64/utils/CurrentLocale.java, src/main/java/org/edumips64/utils/InMemoryConfigStore.java, src/main/java/org/edumips64/utils/JavaPrefsConfigStore.java, src/test/java/org/edumips64/EndToEndTests.java
To avoid issues like #125.
Fixes #130.
Thanks to the best refactoring tool: sed. The substitution from strings to the
corresponding ConfigKey value was done with:
for f in $(find src/main/java/org/edumips64 -name "*.java"); do
while read -r var key; do
sed -i $f -e "s/$var/$key";
done < pairs;
done
Where pairs was a list of
"value" ConfigKey.VALUE
Obtained by grepping ConfigKey.java and slightly manipulating it with vim.
=> Change config keys to be typed

.travis.yml, src/main/java/org/edumips64/Main.java, src/main/java/org/edumips64/MainCLI.java, src/test/java/org/edumips64/EndToEndTests.java
Improve the CLI adding very basic timing.
As a result of the first profiling tests cut down the unit test execution time by 50%.
=> Improve the CLI, speed up tests

src/main/java/org/edumips64/ui/swing/GUIConfig.java, src/main/java/org/edumips64/ui/swing/GUIRegisters.java, src/main/java/org/edumips64/utils/ConfigKey.java, src/main/java/org/edumips64/utils/ConfigStore.java, src/main/java/org/edumips64/utils/CurrentLocale.java
Remove the useless configuration option to toggle MIPS32 aliases instead
of register numbers. We can show both.
Fixes #67
=> Always show MIPS32 register alias

src/main/java/org/edumips64/core/Parser.java, src/test/java/org/edumips64/EndToEndTests.java, src/test/resources/set-bit-sort.s
As discussed in Issue #132, adding a new program as a unit test. It completes in ~3 seconds on my machine as a unit test, making it a good regression test for performance issues.
=> Add set bit sort test

src/main/java/org/edumips64/Main.java, src/main/java/org/edumips64/ui/swing/GUIConfig.java, src/main/java/org/edumips64/utils/CurrentLocale.java
Also warn the user before doing so and allow them to prevent this from
happening.
Fixes #98.
=> Reset the simulation if forwarding is changed

src/main/java/org/edumips64/core/CPU.java, src/main/java/org/edumips64/core/is/HALT.java, src/main/java/org/edumips64/core/is/InstructionInterface.java, src/main/java/org/edumips64/core/is/SYSCALL.java, src/main/java/org/edumips64/core/is/StoppingException.java
This makes the termination flow easier to follow, as most logic is in
the CPU itself.
=> Prevent the instructions from changing CPU status

docs/user/en/src/user-interface.rst, docs/user/it/src/user-interface.rst, src/main/java/org/edumips64/core/CPU.java, src/test/java/org/edumips64/EndToEndTests.java
This is a small hack to fix issue #48.
Fixing it in a more radical way requires a deep restructuring of the
code, which I almost finished. The restructuring is invasive, and I
don't think it's beneficial to do it, as it might introduce subtle bugs
I do not find now.
Therefore, I am choosing to not increment the cycles counter in the last
cycle, explaining it in the manual. The explanation makes sense, but the
end result is not very elegant, as when the user executes the very last
cycle they won't see the cycles counter increasing.
Also fix all tests with hardcoded number of cycles, decrementing them by
one cycle.
=> Don't increment cycle counter in the last cycle

.gitignore, build.gradle
Even if they are not listed in #228, these minor clean-ups are still related to the migration.
=> Minor clean-ups after the Gradle migration

src/main/java/org/edumips64/core/Converter.java, src/main/java/org/edumips64/core/fpu/RegisterFP.java, src/main/java/org/edumips64/core/is/DSRA.java, src/main/java/org/edumips64/core/is/DSRAV.java, src/main/java/org/edumips64/core/is/DSRLV.java, src/main/java/org/edumips64/core/is/SRLV.java
Hello, question about this before I continue: several of the ALU_RType files have the same kind of Codacity recommendations as these. It complains that the final int fields aren't explicitly scoped, and then when I make them private, it complains that they are unused. For these files, I removed them, but since there are so many like this I wanted to see if you want to address it this way or not. I was thinking you might have a reason to ignore these errors for now and leave the fields in place.
Thanks.
Howard
=> Codacity fixes 00

build.gradle
The standalone target, which includes javahelp, depends on it explicitly.
Fixes #247
=> Remove JAR dependency on help files

azure-pipelines.yml
Publish the following artifacts upon CI/CD build:
Close #245 .
=> Publish build artifacts on Azure Pipelines

src/main/java/org/edumips64/Main.java, src/main/java/org/edumips64/MainCLI.java, src/main/java/org/edumips64/core/parser/Parser.java, src/main/java/org/edumips64/ui/swing/CPUSwingWorker.java, src/main/java/org/edumips64/ui/swing/ReportDialog.java, src/main/java/org/edumips64/ui/swing/StatusBar.java, src/main/java/org/edumips64/utils/CurrentLocale.java, src/main/java/org/edumips64/utils/MetaInfo.java
The resulting dialog looks like this:
Note: 
- I modified the parser to return the full code, and created a variable in Main to store it
- I removed the "version" function parameter and attribute of CPUSwingWorker and have it use the attribute of Main instead, since it's an attribute of the application as a whole after all
**Edit**:
- added the CLI error message reporting
- translated to English all CLI console output
- ~~NB: at the moment Main.VERSION etc are not populated when executing the CLI shell - they'd have to be extracted from Main I guess~~
(The ErrorDialog class has not be considered for this - should it be?)
Close #256 
Close #261
=> Improve ReportDialog

.gitignore, src/main/java/org/edumips64/core/CPU.java, src/main/java/org/edumips64/core/fpu/FPPipeline.java, src/main/java/org/edumips64/utils/CycleBuilder.java, src/test/java/org/edumips64/EndToEndTests.java, src/test/java/org/edumips64/TestTookTooLongException.java, src/test/resources/issue304.s
This PR fixes the first bug reported in issue #304, and starts tackling the problem of correctly representing out-of-order instructions in the Cycles UI.
It also add timeouts for end-to-end unit tests to detect infinite loops.
=> Do not incorrectly overwrite EX if FP was executed

src/main/java/org/edumips64/ui/swing/CPUSwingWorker.java, src/main/java/org/edumips64/utils/CycleBuilder.java, src/test/java/org/edumips64/EndToEndTests.java, src/test/resources/infinite-bug-304.s
This fixes issue #304, where some FPU instructions wouldn't get some stages represented in the Cycles UI.
=> Increase CycleElement lookback for Cycles UI

CHANGELOG.md, build.gradle.kts, gradle.properties
No intention to release any time soon, but at least jars will have version 1.2.8.
=> Prep version 1.2.8

snapcraft.yaml
=> Ship JRE, not JDK, and don't pin snap

src/main/java/org/edumips64/client/WebUi.java, src/main/java/org/edumips64/client/ui.js
This removes ugly timeouts and guarantees clean initialization.
=> Initialize JS on GWT onModuleLoad event

src/main/java/org/edumips64/client/ui.js
This effectively resets the simulator state before loading a program.
Closes #338.
=> Call reset() on load

src/main/java/org/edumips64/client/ParserError.java, src/main/java/org/edumips64/client/Pipeline.java, src/main/java/org/edumips64/client/Result.java, src/main/java/org/edumips64/client/ResultFactory.java, src/main/java/org/edumips64/client/Simulator.java, src/main/java/org/edumips64/client/Worker.java, src/main/java/org/edumips64/core/parser/Parser.java, src/webapp/components/Code.js, src/webapp/components/Simulator.js
Basic version, barely working.
TODO (in different PRs)
* handle multiple errors in the same line (#385)
* fix parsing error start/end (#383)
* add a nice indicator of error presence and # of warnings/errors (#384)
* check syntax while the user types (every second or so) (#386)
=> Mark parsing errors in Web UI editor

.github/workflows/deploy.yml, .github/workflows/gradle.yml, docs/developer-guide.md, package-lock.json, package.json, webpack.config.js
- replace "manual" copy of static files to build dir with a webpack plugin
- replace serve with [webpack-dev-server](https://webpack.js.org/guides/development/#using-webpack-dev-server) (which provides live code reloading)
- update pipelines accordingly (remove "deploy" step)
- update dev docs
- remove replaced dependencies
=> Use webpack plugins to copy files and add webpack-dev-server

src/webapp/static/index.html, src/webapp/static/style.css
A couple of style fixes to the memory textarea (I know there are better plans for that as per #344, but in the meantime...): 
- invert the CSS order so that `width:100% height:100%` in style.css is applied to the textarea element (now it's rendered shrunk)
- use same text color as in the other elements, which is set by materialize.css (now it's black)
---
Unrelated to this PR, some feedback on the Web UI:
- it's pretty cool, good job! :+1: 
- the Monaco editor is quite heavy: it makes the js bundle about 2.7MB, from just 300kB with a simple textarea instead... I wonder if there's any way to make it slimmer (or use Ace or something [else](https://en.wikipedia.org/wiki/Comparison_of_JavaScript-based_source_code_editors)) :thinking: 
- etc (other stuff, but no need to be too picky on a …
=> Minor style fixes for memory textarea

src/webapp/components/Code.js
The callback modified hoverCleanups, but also depended on it, which
generated an infinite update loop.
=> Fix recursive update in useEffect

src/webapp/static/style.css
This will prevent the editor from collapsing to 0px height if the initial layout is a 1-column grid, which happens on mobile.
=> Set minimum editor widget height

src/webapp/index.js
This should allow the version to be a first-class dimension in the
dashboard.
=> fix(web): specify version in the AppInsights way

webpack.config.js
This is achieved by removing most Monaco Editor features, preserving the
ones we use or think will be useful.
Bundle size goes from 2.68MB to 2.07MB. Still pretty high.
=> perf(web): reduce bundle size by 22%

renovate.json
Renovate sends several PRs per week, and there is very little value in reviewing them separately.
This also causes a cluttered commit log.
While changing this file, also wait 7 days after any given version is released before sending a PR (to reduce exposure to potential bugs)
=> refactor(renovate): group updates in weekly PRs

.eslintrc.json, package-lock.json, package.json
This prevents JSX from being treated as an error.
=> fix(web): use babel as parser for eslint

package-lock.json, package.json
The recent 5.0.0-beta17/18 break the build. By pinning the latest 4.x,
renovatebot should not suggest using unstable 5.x versions.
=> chore(deps): pin latest stable webpack

.github/workflows/gradle.yml, CHANGELOG.md, build.gradle.kts, docs/developer-guide.md, scripts/edumips64-snap-wrapper.sh, snapcraft.yaml
Start-up now depends on PicoCLI anyway, so it's not practical to have
a JAR with no embedded dependencies.
Also update the CHANGELOG and the developer guide.
=> Remove no-deps JAR

package-lock.json, package.json
This fixes a security alert generated by dependabot on GitHub.
Also update self-signed (by "npm audit fix").
=> fix: install recent node-forge

build.gradle.kts, docs/developer-guide.md, src/main/java/org/edumips64/core/is/ADDI.java, src/main/java/org/edumips64/core/is/ADDIU.java, src/main/java/org/edumips64/core/is/ALU_IType.java, src/main/java/org/edumips64/core/is/ANDI.java, src/main/java/org/edumips64/core/is/DADDI.java, src/main/java/org/edumips64/core/is/DADDIU.java, src/main/java/org/edumips64/core/is/LUI.java, src/main/java/org/edumips64/core/is/ORI.java, src/main/java/org/edumips64/core/is/SLTI.java, src/main/java/org/edumips64/core/is/SLTIU.java, src/main/java/org/edumips64/core/is/XORI.java
The fix for issue 475 is to explicitly override `ALU_IType.IMM_FIELD` in `LUI` to the value of `1`.
=> fix: fix issue 475 and clean up some minor warnings

src/main/java/org/edumips64/core/is/ALU_IType.java, src/main/java/org/edumips64/core/is/LUI.java
When LUI changes ALU_IType.IMM_FIELD, it changes it for all I-Type ALU
instructions, which makes them misbehave horribly and subtly.
This fix makes IMM_FIELD non-static, therefore making it safe for LUI to
change it.
The change was tested by testing jr-raw.s before and after running
some code with the LUI instruction.
Before the fix, jr-raw would go into a loop when ran after the code with
LUI.
After the fix, jr-raw always behaves correctly.
Unit tests for LUI are coming in #488.
=> fix: don't change static field in ALU_IType

docs/user/common_conf.py
The JavaHelp HTML viewer is pretty old and doesn't seem to digest well
specifying the charset only with the <meta charset=".." />
tag/attribute.
This change makes Sphinx output HTML that specifies the charset in a
different way that seems to work well across all platforms.
HTML diff for one file:
```
(docs-1.2.8) 14:34 edumips64 (fix/docs)$ diff build/docs/en/html/fpu.html build-1.2.8-554f52e/docs/en/html/fpu.html 
5,7c5
<     <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
---
>     <meta charset="utf-8" />
11,15c9,13
<     <script id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
< …
```
=> fix: do not use HTML5 in help

docs/user/en/src/index.rst, docs/user/it/src/index.rst, readme.md, src/main/java/org/edumips64/utils/CurrentLocale.java, src/test/resources/hailstoneenglish.s, src/webapp/data/SampleProgram.js, utils/list-mentioned-issues-since-last-release.sh, utils/submit-coverity.sh, utils/update-gh-pages.sh
I noticed the manual was still referencing the old URL so I did a find and replace all over the project (except in a couple of places where it doesn't make sense, e.g. gitter chat).
=> Chore: find and replace project name in URLs

package-lock.json, package.json, webpack.config.js
This couldn't be done by dependabot due to some tricky non-backwards-compatible changes and upstream bugs.
=> chore(deps): upgrade to latest webpack

.github/workflows/pr-deploy.yml
Has to be done, because it's now a required check, and I found no way to bypass it.
=> fix: run deploy-ui on all PRs

src/test/java/org/edumips64/CliRunnerTest.java
Use in-memory preferences engine instead of the one based on Java
preferences during unit tests. This ensures hermetic execution and
prevents bugs caused by mismatched text in languages other than English.
Fixes #499
=> fix: do not load Java preferences during tests

build.gradle.kts, docs/developer-guide.md, docs/requirements.txt
Adopt ru.vyarus.use-python, that abstracts away installing Python dependencies and running Python scripts across multiple platforms, with the added benefit of allowing the use of a virtual environment to install build-time Python dependencies.
=> feat: adopt Gradle task for Python

.github/workflows/codeql-analysis.yml, .github/workflows/deploy.yml, .github/workflows/gradle.yml, .github/workflows/pr-deploy.yml
Renovate couldn't do it because it's a breaking change that requires a
new option.
=> chore(deps): migrate to setup-java v2

.github/workflows/ci.yml
Running on master push will execute tests against
the previously deployed version of the code (due to
the deployment latency), thus giving a false sense of
security.
=> fix: only run test-web on PR

snapcraft.yaml
It's unnecessary because it's already done by the Gradle build.
=> tweak: remove pip install from snap build

snapcraft.yaml
Should fix issues running the snap where JRE 11 is picked, and class files built
with JDK 17 are not compatible with older JREs.
=> fix: point snapcraft JAVA_HOME to JRE 17

AUTHORS.md, CHANGELOG.md, RELEASE_NOTES.md, build.gradle.kts, docs/developer-guide.md, gradle.properties, scripts/edumips64-snap-wrapper.sh, snapcraft.yaml
Update documentation and version numbers.
Changelog:
- New Snapcraft packages for armhf (e.g. Raspberry PI) and other architectures
- Parser incorrectly interprets hexadecimal immediates (Issue #450)
- Some floating-point division cycles missing in Cycles window (Issue #646)
- Infinite RAW stall in floating-point code (Issue #304) (yes, *again*)
- Migrated to JDK (and JRE) 17
=> release: 1.2.10

.github/workflows/ci.yml, snapcraft.yaml
This creates a smaller snap (fixes #657) and also removes a dangling
symlink that makes recent snaps fail snapcraft validation (fixes #656).
=> fix: remove JDK/JRE 11 from snap and test it

build.gradle.kts, snapcraft.yaml
This is necessary for Sphinx >= 6, and apparently the core18 snap base comes with 3.6. More modern bases don't have the gradle plugin, so this seems to be the quickest fix for the build.
=> chore: use Python3.8 for snap build

build.gradle.kts, src/main/java/org/edumips64/ui/swing/ErrorDialog.java, src/main/java/org/edumips64/ui/swing/GUIAbout.java, src/main/java/org/edumips64/ui/swing/GUICycles.java, src/main/java/org/edumips64/ui/swing/GUIPipeline.java, src/test/java/org/edumips64/CliRunnerTest.java
These changes should make merging #772 possible, by using logical font names and specifying the encoding of source files. 
This also fixes the names of some test methods that were triggering Codacy errors.
=> Prepare for Simplified Chinese support

docs/user/en/src/instructions.rst, docs/user/it/src/instructions.rst, src/main/java/org/edumips64/core/is/DMUHU.java, src/main/java/org/edumips64/core/is/DMULU.java, src/main/java/org/edumips64/core/is/InstructionBuilder.java, src/main/java/org/edumips64/core/parser/Parser.java, src/test/java/org/edumips64/BaseParsingTest.java, src/test/java/org/edumips64/BaseWithInstructionBuilderTest.java, src/test/java/org/edumips64/EndToEndTests.java, src/test/java/org/edumips64/core/MemoryTest.java, src/test/java/org/edumips64/core/ParserTest.java, src/test/java/org/edumips64/core/is/DMUHUTest.java, src/test/java/org/edumips64/core/is/DMULUTest.java, src/test/resources/dmulu-dmuhu.s, src/test/resources/dmulu-simple-test.s, src/test/resources/dmulu.s
DMULU was implemented incorrectly as an alias to DMULTU.
This was correct when we first implemented it, as it was a WinMIPS64-specific alias
and not a real MIPS64 instruction. However, the Release 6 of MIPS64 introduced
DMULU with a different semantics.
This change adds it and also implements its complement DMUHU.
As part of this, refactor a bit the tests to add a test harness with parsing
facilities in order to easily test the 32-bit instruction representations.
Also add unit tests, some end-to-end tests and English and Italian documentation
for DMULU and DMUHU.
Thanks @smallg0at for spotting this error and reporting it in #779, which is now fixed.
=> Fix DMULU and add DMUHU

.github/workflows/ci.yml
The current deployment URL for PRs is incorrect, as it points to the root of the domain and it makes all resources resolve to the latest master.
This PR updates the deployment URL so that it actually points to the right PR directory.
=> Fix deployment URL for PRs

snapcraft.yaml
This should fix #803, as with the old config snapcraft would always fetch and build the master branch.
=> fix: build source locally

build.gradle.kts
Should fix the bug found while preparing 1.3.0 (see #819)
=> fix: build Italian docs for 'it' language

renovate.json
This will add the dependency dashboard at least.
Right now dependency grouping doesn't work well, because we need to keep sphinx back to 7.1.x but we want to update other dependencies. Let's see if there is a more flexible way of achieving this goal.
=> Use recommended renovate settings

src/main/java/org/edumips64/client/ResultFactory.java, src/main/java/org/edumips64/client/Simulator.java, src/main/java/org/edumips64/client/Worker.java, src/webapp/components/CpuStatusDisplay.js, src/webapp/components/ErrorList.js, src/webapp/components/Header.js, src/webapp/components/Simulator.js, src/webapp/index.js
* fix #814 
* fix web UI warnings:
* `<div>` in `<p>`
* migrate from old Client Rendering API to new one
* non-unique keys in error list component
* add CPU Status indication
* enable @smallg0at's code to conditionally disable the Load button
=> Web UI improvements

package.json
This reverts commit 8045ea386bf53a10255f5193e6aaf096ecf54f6b.
With required checks, this change should not get into master anymore.
=> Revert "chore(deps): update dependency eslint to v9"

docs/user/en/src/.readthedocs.yaml, docs/user/it/src/.readthedocs.yaml, docs/user/zh/src/.readthedocs.yaml
Paths in .readthedocs.yaml must be relative to the root of the repo.
This PR changes the config file for all projects (one per language) to use root-repo-relative paths for the Sphinx configuration and requirements files.
Fixes #1204
=> fix: update RTD YAML to use root-repo-relative paths

src/main/java/org/edumips64/core/IOManager.java, src/main/java/org/edumips64/core/SymbolTable.java, src/main/java/org/edumips64/core/fpu/FPInstructionUtils.java, src/main/java/org/edumips64/core/parser/Parser.java, src/main/java/org/edumips64/ui/swing/GUIHelp.java, src/main/java/org/edumips64/ui/swing/MultiLineBasicTableUI.java, src/test/java/org/edumips64/core/fpu/FPInstructionUtilsTest.java
Address potential null dereference scenarios, remove deprecated URL constructor, and enhance error handling by returning empty strings for invalid inputs.
Add more unit tests for FPInstructionUtils.
=> Fix null dereference issues and improve error handling

src/main/java/org/edumips64/client/Result.java, src/main/java/org/edumips64/client/ResultFactory.java, src/main/java/org/edumips64/client/Simulator.java, src/webapp/components/Simulator.js, src/webapp/components/StdOut.js, src/webapp/data/SampleProgram.js
Contributes to Web UI: basic SYSCALL support #1224
Also add a simpler example program.
=> feat(web): implement stdout support

utils/find-instructions.sh
Considered "critical" by Codacy
=> fix: add shebang in find-instructions.sh

.github/workflows/ci.yml
By default, secrets are not available from workflows triggered
by external PRs, which go through the pull_request event.
This PR adds a way to execute workflows for those PRs via
the (more dangerous) event pull_request_target, which runs
in the context of the base branch and provides secrets, and
in this case is triggered by the "safe to test" label, which can
only be set by maintainers.
Fixes #1281.
=> fix(dev): allow actions requiring secrets from safe external PRs

.github/workflows/ci.yml
This should have access to environment secrets even from external forks.
It should be safe because the environment is protected by a manual approval step.
=> fix: switch to pull_request_target

src/webapp/components/Simulator.js
StdOut section should be expanded only when inspected by user, coherently with Registers, Pipeline, Memory.
Also, many programs just don't produce any stdout and keeping it expanded with a blank box consumes a lot of space on the right side, making settings tab not visible in many resolutions. Hopefully, Settings tab will be filled with more controls that user wants to access easily.
=> Remove default expansion from StdOut's Accordion

src/webapp/components/Code.js
This simple PR completes the missing classes of tokens (registers, directives, etc...) and also add all the missing instructions of MIPS64. See effect below.
**OLD ----------------->**
**NEW ---------------->**
=> WebUI Syntax Coloring
